version: '3.8'

services:
  bot:
    build: ./bot
    env_file: .env
    restart: unless-stopped
    depends_on:
      - db
      - api

  api:
    build: ./web/backend
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db

  frontend:
    build: ./web/frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://api:8000

  db:
    image: postgres:13
    env_file: .env.db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


volumes:
  postgres_data: